In [10]:
#Import Libraries

import pandas as pd
import numpy as np

#Import Dataset
movies = pd.read_csv('tmdb_5000_movies.csv')
credit = pd.read_csv('tmdb_5000_credits.csv')

movies=movies.merge(credit)

In [11]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   str
 2   homepage              1713 non-null   str
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   str
 5   original_language     4809 non-null   str
 6   original_title        4809 non-null   str
 7   overview              4806 non-null   str
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   str
 10  production_countries  4809 non-null   str
 11  release_date          4808 non-null   str
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   str
 15  status                4809 non-null   str
 16  tagline               3965 non-null   str
 17  title                 4809 non-null   str
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   str
 22  crew                  4809 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 864.2 KB

In [12]:
movies=movies[['movie_id','title','overview','genres','keywords','cast' ,'crew' ]]

In [13]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.dropna(inplace=True)

In [16]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
movies.duplicated().sum()

np.int64(0)

In [18]:
movies.head(3)

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...

[3 rows x 7 columns]

In [19]:
import ast

def convert1(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [20]:
movies['genres']=movies['genres'].apply(convert1)

In [21]:
movies['keywords']=movies['keywords'].apply(convert1)

In [22]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [23]:
def convert2(obj):
    L =[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter +=1
        else:
            break
    return L

In [24]:
movies['cast']=movies['cast'].apply(convert2)

In [25]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [26]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1       285  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    206647  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3     49026  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     49529  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 7 columns]

In [27]:
movies['overview']=movies['overview'].apply(lambda x : x.split())

In [28]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [29]:
movies.head()

   movie_id  ...                                               crew
0     19995  ...  [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
1       285  ...  [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
2    206647  ...  [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
3     49026  ...  [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...
4     49529  ...  [[, {, ", c, r, e, d, i, t, _, i, d, ", :, , "...

[5 rows x 7 columns]

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies.iloc[0].tags

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 '[',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '2',
 'f',
 'e',
 '4',
 '8',
 '0',
 '0',
 '9',
 '2',
 '5',
 '1',
 '4',
 '1',
 '6',
 'c',
 '7',
 '5',
 '0',
 'a',
 'c',
 'a',
 '2',
 '3',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'E',
 'd',
 'i',
 't',
 'i',
 'n',
 'g',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '0',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '7',
 '2',
 '1',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'E',
 'd',
 'i',
 't',
 'o',
 'r',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'S',
 't',
 'e',
 'p',
 'h',
 'e',
 'n',
 '',
 'E',
 '.',
 '',
 'R',
 'i',
 'v',
 'k',
 'i',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '3',
 '9',
 'c',
 '4',
 '7',
 'e',
 'c',
 'c',
 '3',
 'a',
 '3',
 '6',
 '8',
 '1',
 '0',
 'e',
 '3',
 '0',
 '0',
 '1',
 'f',
 '8',
 '7',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'A',
 'r',
 't',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '2',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '4',
 '9',
 '6',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'P',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 '',
 'D',
 'e',
 's',
 'i',
 'g',
 'n',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'R',
 'i',
 'c',
 'k',
 '',
 'C',
 'a',
 'r',
 't',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '4',
 '4',
 '9',
 '1',
 'c',
 '8',
 '9',
 'c',
 '3',
 'a',
 '3',
 '6',
 '8',
 '0',
 'f',
 'b',
 '4',
 '0',
 '0',
 '1',
 'c',
 'f',
 '7',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'S',
 'o',
 'u',
 'n',
 'd',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '0',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '0',
 '0',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'S',
 'o',
 'u',
 'n',
 'd',
 '',
 'D',
 'e',
 's',
 'i',
 'g',
 'n',
 'e',
 'r',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'C',
 'h',
 'r',
 'i',
 's',
 't',
 'o',
 'p',
 'h',
 'e',
 'r',
 '',
 'B',
 'o',
 'y',
 'e',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '4',
 '4',
 '9',
 '1',
 'c',
 'b',
 '7',
 '0',
 'e',
 '0',
 'a',
 '2',
 '6',
 '7',
 '4',
 '8',
 '0',
 '0',
 '0',
 '1',
 'b',
 'd',
 '0',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'S',
 'o',
 'u',
 'n',
 'd',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '0',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '0',
 '0',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'S',
 'u',
 'p',
 'e',
 'r',
 'v',
 'i',
 's',
 'i',
 'n',
 'g',
 '',
 'S',
 'o',
 'u',
 'n',
 'd',
 '',
 'E',
 'd',
 'i',
 't',
 'o',
 'r',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'C',
 'h',
 'r',
 'i',
 's',
 't',
 'o',
 'p',
 'h',
 'e',
 'r',
 '',
 'B',
 'o',
 'y',
 'e',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '3',
 '9',
 'c',
 '4',
 'a',
 '4',
 'c',
 'c',
 '3',
 'a',
 '3',
 '6',
 '8',
 '1',
 '0',
 'c',
 '9',
 '0',
 '0',
 '2',
 '1',
 '0',
 '1',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'P',
 'r',
 'o',
 'd',
 'u',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '1',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '2',
 '6',
 '2',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'C',
 'a',
 's',
 't',
 'i',
 'n',
 'g',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'M',
 'a',
 'l',
 'i',
 '',
 'F',
 'i',
 'n',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '5',
 '4',
 '4',
 'e',
 'e',
 '3',
 'b',
 '9',
 '2',
 '5',
 '1',
 '4',
 '1',
 '4',
 '9',
 '9',
 'f',
 '0',
 '0',
 '0',
 '8',
 'f',
 'c',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'S',
 'o',
 'u',
 'n',
 'd',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '2',
 ',',
 '',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '7',
 '2',
 '9',
 ',',
 '',
 '"',
 'j',
 'o',
 'b',
 '"',
 ':',
 '',
 '"',
 'O',
 'r',
 'i',
 'g',
 'i',
 'n',
 'a',
 'l',
 '',
 'M',
 'u',
 's',
 'i',
 'c',
 '',
 'C',
 'o',
 'm',
 'p',
 'o',
 's',
 'e',
 'r',
 '"',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'J',
 'a',
 'm',
 'e',
 's',
 '',
 'H',
 'o',
 'r',
 'n',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'c',
 'r',
 'e',
 'd',
 'i',
 't',
 '_',
 'i',
 'd',
 '"',
 ':',
 '',
 '"',
 '5',
 '2',
 'f',
 'e',
 '4',
 '8',
 '0',
 '0',
 '9',
 '2',
 '5',
 '1',
 '4',
 '1',
 '6',
 'c',
 '7',
 '5',
 '0',
 'a',
 'c',
 '9',
 'c',
 '3',
 '"',
 ',',
 '',
 '"',
 'd',
 'e',
 'p',
 'a',
 'r',
 't',
 'm',
 'e',
 'n',
 't',
 '"',
 ':',
 '',
 '"',
 'D',
 'i',
 'r',
 'e',
 'c',
 't',
 'i',
 'n',
 'g',
 '"',
 ',',
 '',
 '"',
 'g',
 'e',
 'n',
 'd',
 'e',
 'r',
 '"',
 ':',
 '',
 '2',
 ',',
 '',
 '"',
 ...]

In [32]:
movies.info()

<class 'pandas.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4806 non-null   int64
 1   title     4806 non-null   str
 2   overview  4806 non-null   object
 3   genres    4806 non-null   object
 4   keywords  4806 non-null   object
 5   cast      4806 non-null   object
 6   crew      4806 non-null   object
 7   tags      4806 non-null   object
dtypes: int64(1), object(6), str(1)
memory usage: 337.9+ KB

In [33]:
new_df = movies[['movie_id' ,'title' ,'tags']]

In [34]:
new_df.head()

   movie_id  ...                                               tags
0     19995  ...  [In, the, 22nd, century,, a, paraplegic, Marin...
1       285  ...  [Captain, Barbossa,, long, believed, to, be, d...
2    206647  ...  [A, cryptic, message, from, Bond’s, past, send...
3     49026  ...  [Following, the, death, of, District, Attorney...
4     49529  ...  [John, Carter, is, a, war-weary,, former, mili...

[5 rows x 3 columns]

In [35]:
new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x))

In [36]:
new_df

      movie_id  ...                                               tags
0        19995  ...  In the 22nd century, a paraplegic Marine is di...
1          285  ...  Captain Barbossa, long believed to be dead, ha...
2       206647  ...  A cryptic message from Bond’s past sends him o...
3        49026  ...  Following the death of District Attorney Harve...
4        49529  ...  John Carter is a war-weary, former military ca...
...        ...  ...                                                ...
4804      9367  ...  El Mariachi just wants to play his guitar and ...
4805     72766  ...  A newlywed couple's honeymoon is upended by th...
4806    231617  ...  "Signed, Sealed, Delivered" introduces a dedic...
4807    126186  ...  When ambitious New York attorney Sam is sent t...
4808     25975  ...  Ever since the second grade when he first saw ...

[4806 rows x 3 columns]

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x : x.lower())

In [38]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [39]:
new_df['tags']=new_df['tags'].apply(stem)

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000 , stop_words='english')

vector = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity =cosine_similarity(vector)

[(1214, np.float64(0.29061909685954823)),
 (3728, np.float64(0.26401000024165)),
 (507, np.float64(0.26130213378560535)),
 (539, np.float64(0.2537477434955704)),
 (2405, np.float64(0.25070610528195014))]

In [60]:
def recommend(movie):

    movies_index =new_df[new_df['title'] == movie].index[0]
    distances = similarity[movies_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True , key=lambda x :x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [64]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
10th & Wolf
The Dark Knight Rises

In [65]:
import pickle

pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))